In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.metrics

In [4]:
df = pd.DataFrame({"x": [-2, -1, 1, 2],
              "y": [-1, -1, 1, 1],
              "class": ["A", "B", "A", "B"]})

df

   x  y class
0 -2 -1     A
1 -1 -1     B
2  1  1     A
3  2  1     B

In [ ]:
# plot points as x, y

In [9]:
df["x_map"] = df['x']**2
df

   x  y class  x_map
0 -2 -1     A      4
1 -1 -1     B      1
2  1  1     A      1
3  2  1     B      4

In [ ]:
# plot points again as x, x^2